inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-inflector
  - ./config/initializers/inflections # My custom rule file

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 40

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5