inherit_from: .rubocop_todo.yml

# inherit_gem:
#   test-prof: config/rubocop-rspec.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  # - rubocop-inflector
  - ./config/initializers/inflections # My custom rule file

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

# Style/StringConcatenation:


Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Max: 40

RSpec/ExampleLength:
  Max: 20

RSpec/ContextWording:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 5