version: '3.8'

services:
  db:
    image: mysql:8.0.29-oracle
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3307:3306'
