version: '3.8'

services:
  db:
    image: mysql:8.0.29-oracle
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - mysql-db:/var/lib/mysql
      - ./db:/var/lib/mysql
  api:
    tty: true
    stdin_open: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: ./Dockerfile.prod
    ports:
      - 3001:3000
    volumes:
      - public-data:/app/public
      - tmp-data:/app/tmp
      - .:/app
  web:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx:/app/public
      - ./tmp/sockets:/app/tmp/sockets
      - public-data:/app/public
      - tmp-data:/app/tmp
    # volumes:
    ports:
      - 80:80
    depends_on:
      - api
volumes:
  mysql-db:
    driver: local
  public-data:
  tmp-data: