version: '3.8'

services:
  db:
    image: mysql:8.0.29-oracle
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 4306:3306
    volumes:
      - mysql-db:/var/lib/mysql
  api:
    tty: true
    stdin_open: true
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    volumes:
      - .:/app
    command: bundle exec rails s -b '0.0.0.0'
volumes:
  mysql-db:
    driver: local
